apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: jenkins-charts
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ja80rincon/jenkins-charts.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins-charts
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/jenkins/
      version: "2.332.2"
      sourceRef:
        kind: GitRepository
        name: jenkins-charts
        namespace: flux-system
      interval: 1m
